project:
  type: website  
  output-dir: docs


website:
  title: "CELP Lab Field Guide & Species Codes"
  navbar:
    left:
      - href: all.html
        text: All
      - text: By Habitat
        menu:
          - href: rocky_intertidal.html
            text: Rocky Intertidal
          - href: rocky_subtidal.html
            text: Rocky Subtidal
          - href: marsh.html
            text: Salt marsh  
            
      - text: KEEN
        menu:
          - href: keen_quads.html
            text: Quad Species
          - href: keen_swath.html
            text: Swath Species
          - href: keen_upc.html
            text: Uniform Point Count Species

      - text: Boston Harbor Islands Sampling
        menu:
          - href: bhi_quads.html
            text: Quad Species
          - href: bhi_rov.html
            text: ROV Species
          - href: bhi_bruv_briv.html
            text: BRUV/BRIV Species
          - href: bhi_farms.html
            text: FARMS Species
            
      - text: Living Seawall Sampling
        menu:
          - href: lsw_quads.html
            text: Quad Species
          - href: lsw_microquad.html
            text: Microquad Species
          - href: lsw_camera.html
            text: Mobile Camera Species

    right:
      - text: "CELP Lab Homepage"
        href: http://celp-lab.org
           

  page-footer: 
    left: '[![](/images/New_UMB_Logo_news_042522.jpg){width="50%"}](https://www.umb.edu/)'
    right: 'Made with {{< fa brands r-project size=2x >}} and 
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" height=20px}](https://quarto.org/) <br>
      Code at [{{< fa brands github>}}](https://github.com/celp-lab/species_lists/)<br>'
      
format:
  html:
    mainfont: Avenir
    css: styles.css
    toc: true


